=== 1liornatan/Alternative-Banking-System/Engine/src/resources/ABS-V1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="abs-customers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="abs-customer" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="abs-customer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="abs-balance"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="abs-total-yaz-time" type="xs:int"/>
	<xs:element name="abs-pays-every-yaz" type="xs:int"/>
	<xs:element name="abs-owner" type="xs:string"/>
	<xs:element name="abs-loans">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="abs-loan" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="abs-loan">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="abs-owner"/>
				<xs:element ref="abs-category"/>
				<xs:element ref="abs-capital"/>
				<xs:element ref="abs-total-yaz-time"/>
				<xs:element ref="abs-pays-every-yaz"/>
				<xs:element ref="abs-intrist-per-payment"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="abs-intrist-per-payment" type="xs:int"/>
	<xs:element name="abs-descriptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="abs-categories"/>
				<xs:element ref="abs-loans"/>
				<xs:element ref="abs-customers"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="abs-category" type="xs:string"/>
	<xs:element name="abs-categories">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="abs-category" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="abs-capital" type="xs:int"/>
	<xs:element name="abs-balance" type="xs:int"/>
</xs:schema>

=== 1liornatan/Alternative-Banking-System/Engine/src/resources/ex1-big.xml
<abs-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ABS-V1.xsd">
	<abs-categories>
		<abs-category>Setup a business</abs-category>
		<abs-category>Overdraft cover</abs-category>
		<abs-category>Investment</abs-category>
		<abs-category>Happy Event</abs-category>
		<abs-category>Renovate</abs-category>
	</abs-categories>
	<abs-loans>
		<abs-loan id="stock market introduction">
			<abs-owner>Menash</abs-owner>
			<abs-category>Investment</abs-category>
			<abs-capital>2400</abs-capital>
			<abs-total-yaz-time>12</abs-total-yaz-time>
			<abs-pays-every-yaz>1</abs-pays-every-yaz>
			<abs-intrist-per-payment>5</abs-intrist-per-payment>
		</abs-loan>
		<abs-loan id="build a room">
			<abs-owner>Avrum</abs-owner>
			<abs-category>Renovate</abs-category>
			<abs-capital>3000</abs-capital>
			<abs-total-yaz-time>10</abs-total-yaz-time>
			<abs-pays-every-yaz>2</abs-pays-every-yaz>
			<abs-intrist-per-payment>3</abs-intrist-per-payment>
		</abs-loan>
		<abs-loan id="Bar Mitzva !">
			<abs-owner>Mosh</abs-owner>
			<abs-category>Happy Event</abs-category>
			<abs-capital>2500</abs-capital>
			<abs-total-yaz-time>25</abs-total-yaz-time>
			<abs-pays-every-yaz>5</abs-pays-every-yaz>
			<abs-intrist-per-payment>15</abs-intrist-per-payment>
		</abs-loan>
		<abs-loan id="Wedding">
			<abs-owner>Levana</abs-owner>
			<abs-category>Happy Event</abs-category>
			<abs-capital>24000</abs-capital>
			<abs-total-yaz-time>24</abs-total-yaz-time>
			<abs-pays-every-yaz>2</abs-pays-every-yaz>
			<abs-intrist-per-payment>5</abs-intrist-per-payment>
		</abs-loan>
		<abs-loan id="I don't have money">
			<abs-owner>Tikva</abs-owner>
			<abs-category>Overdraft cover</abs-category>
			<abs-capital>4000</abs-capital>
			<abs-total-yaz-time>10</abs-total-yaz-time>
			<abs-pays-every-yaz>1</abs-pays-every-yaz>
			<abs-intrist-per-payment>3</abs-intrist-per-payment>
		</abs-loan>
		<abs-loan id="Damn the banks">
			<abs-owner>Menash</abs-owner>
			<abs-category>Setup a business</abs-category>
			<abs-capital>42000</abs-capital>
			<abs-total-yaz-time>21</abs-total-yaz-time>
			<abs-pays-every-yaz>7</abs-pays-every-yaz>
			<abs-intrist-per-payment>20</abs-intrist-per-payment>
		</abs-loan>				
	</abs-loans>
	<abs-customers>
		<abs-customer name="Menash">
			<abs-balance>5000</abs-balance>
		</abs-customer>
		<abs-customer name="Avrum">
			<abs-balance>1000</abs-balance>
		</abs-customer>
		<abs-customer name="Tikva">
			<abs-balance>10000</abs-balance>
		</abs-customer>
		<abs-customer name="Shosh">
			<abs-balance>20000</abs-balance>
		</abs-customer>
		<abs-customer name="Mosh">
			<abs-balance>15000</abs-balance>
		</abs-customer>
		<abs-customer name="Bina">
			<abs-balance>2000</abs-balance>
		</abs-customer>
		<abs-customer name="Levana">
			<abs-balance>100</abs-balance>
		</abs-customer>
	</abs-customers>
</abs-descriptor>
